# Generated by Django 4.2.30 on 2026-06-18 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='맛집 이름')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('region', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('부산', '부산'), ('대구', '대구'), ('대전', '대전'), ('광주', '광주'), ('기타', '기타')], max_length=10, verbose_name='지역')),
                ('category', models.CharField(choices=[('한식', '한식'), ('일식', '일식'), ('중식', '중식'), ('양식', '양식'), ('카페', '카페'), ('디저트', '디저트'), ('술집', '술집'), ('기타', '기타')], max_length=10, verbose_name='음식종류')),
                ('price_range', models.CharField(choices=[('1만원이하', '1만원 이하'), ('1~3만원', '1~3만원'), ('3만원이상', '3만원 이상')], max_length=10, verbose_name='가격대')),
                ('vibe', models.CharField(choices=[('조용한', '조용한'), ('활기찬', '활기찬'), ('로맨틱', '로맨틱'), ('캐주얼', '캐주얼'), ('비즈니스', '비즈니스')], max_length=10, verbose_name='분위기')),
                ('facilities', models.JSONField(blank=True, default=list, verbose_name='편의시설')),
                ('meal_time', models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁')], max_length=5, verbose_name='방문 시간대')),
                ('rating_taste', models.IntegerField(verbose_name='음식 맛')),
                ('rating_mood', models.IntegerField(verbose_name='분위기')),
                ('rating_service', models.IntegerField(verbose_name='서비스')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='restaurants/', verbose_name='사진')),
                ('visited_date', models.DateField(blank=True, null=True, verbose_name='방문일')),
                ('revisit', models.BooleanField(default=True, verbose_name='재방문 의향')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
