# Generated by Django 4.2.30 on 2026-06-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='사진'),
        ),
    ]
