from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from restaurants.models import Restaurant
import datetime

User = get_user_model()

RESTAURANTS = [
    # 서울 · 강남
    {
        "name": "온지음 맛공간",
        "address": "서울 종로구 북촌로5나길 3",
        "region": "서울",
        "category": "한식",
        "price_range": "3만원대",
        "vibe": "고즈넉한",
        "meal_time": "저녁",
        "rating_taste": 5,
        "rating_mood": 5,
        "rating_service": 5,
        "facilities": ["주차", "예약가능", "단체석"],
        "memo": "궁중 한식의 정수. 코스 요리 하나하나가 예술이고 공간도 한옥 분위기라 너무 좋았다. 예약은 최소 한 달 전에 해야 함.",
        "revisit": True,
        "visited_date": datetime.date(2024, 3, 15),
    },
    {
        "name": "광화문 국밥",
        "address": "서울 종로구 새문안로 92",
        "region": "서울",
        "category": "한식",
        "price_range": "1만원 미만",
        "vibe": "로컬 감성",
        "meal_time": "점심",
        "rating_taste": 5,
        "rating_mood": 3,
        "rating_service": 4,
        "facilities": ["포장가능"],
        "memo": "순대국밥 한 그릇이 이렇게 완벽할 수 있다니. 뚝배기에 나오는 국물이 진하고 깔끔. 줄 서도 먹을 가치 있음.",
        "revisit": True,
        "visited_date": datetime.date(2024, 5, 20),
    },
    {
        "name": "정식당",
        "address": "서울 강남구 선릉로158길 11",
        "region": "서울",
        "category": "한식",
        "price_range": "5만원 이상",
        "vibe": "모던 / 세련된",
        "meal_time": "저녁",
        "rating_taste": 5,
        "rating_mood": 5,
        "rating_service": 5,
        "facilities": ["예약가능", "주차", "와인/주류"],
        "memo": "미슐랭 2스타. 현대적으로 재해석한 한식 파인다이닝. 갈비 타르타르가 특히 인상적이었음. 특별한 날 강력 추천.",
        "revisit": True,
        "visited_date": datetime.date(2024, 1, 28),
    },
    {
        "name": "스시 사이토",
        "address": "서울 강남구 압구정로80길 21",
        "region": "서울",
        "category": "일식",
        "price_range": "5만원 이상",
        "vibe": "모던 / 세련된",
        "meal_time": "저녁",
        "rating_taste": 5,
        "rating_mood": 4,
        "rating_service": 5,
        "facilities": ["예약가능", "주류", "와인/주류"],
        "memo": "오마카세 코스가 정말 훌륭했다. 제철 재료를 고집하는 게 느껴지는 스시. 주방장이 직접 설명해줘서 더 맛있었음.",
        "revisit": True,
        "visited_date": datetime.date(2024, 4, 5),
    },
    {
        "name": "가온",
        "address": "서울 강남구 선릉로 708",
        "region": "서울",
        "category": "한식",
        "price_range": "5만원 이상",
        "vibe": "고즈넉한",
        "meal_time": "저녁",
        "rating_taste": 5,
        "rating_mood": 5,
        "rating_service": 5,
        "facilities": ["예약가능", "단체석", "와인/주류", "주차"],
        "memo": "미슐랭 3스타 한식. 전통 식재료를 활용한 코스가 감동적. 그릇 하나하나도 공예 작품 수준. 인생 식당.",
        "revisit": True,
        "visited_date": datetime.date(2023, 12, 31),
    },
    {
        "name": "연남동 경양식 1920",
        "address": "서울 마포구 연남동 227-27",
        "region": "서울",
        "category": "양식",
        "price_range": "2만원대",
        "vibe": "레트로 / 빈티지",
        "meal_time": "점심",
        "rating_taste": 4,
        "rating_mood": 5,
        "rating_service": 4,
        "facilities": ["예약가능"],
        "memo": "1920년대 경양식 분위기 그대로. 돈까스와 함박스테이크가 클래식하게 맛있음. 공간 자체가 포토스팟.",
        "revisit": True,
        "visited_date": datetime.date(2024, 6, 8),
    },
    {
        "name": "망원동 오래된 국수",
        "address": "서울 마포구 망원동 392-1",
        "region": "서울",
        "category": "한식",
        "price_range": "1만원 미만",
        "vibe": "로컬 감성",
        "meal_time": "점심",
        "rating_taste": 4,
        "rating_mood": 3,
        "rating_service": 3,
        "facilities": ["포장가능"],
        "memo": "칼국수 한 그릇에 행복해질 수 있다는 걸 다시 깨달았다. 주인 할머니가 직접 반죽해서 써는 면발이 쫀득.",
        "revisit": True,
        "visited_date": datetime.date(2024, 7, 2),
    },
    {
        "name": "이태원 알레그리아",
        "address": "서울 용산구 이태원로 200",
        "region": "서울",
        "category": "양식",
        "price_range": "3만원대",
        "vibe": "이국적인",
        "meal_time": "저녁",
        "rating_taste": 4,
        "rating_mood": 5,
        "rating_service": 4,
        "facilities": ["예약가능", "와인/주류", "야외석"],
        "memo": "스페인식 타파스 바. 하몽이볼레로와 감바스가 진짜. 와인 리스트도 알차고 분위기가 이태원스러움.",
        "revisit": True,
        "visited_date": datetime.date(2024, 5, 11),
    },
    # 부산
    {
        "name": "초량밀면",
        "address": "부산 동구 초량중로 34",
        "region": "부산",
        "category": "한식",
        "price_range": "1만원 미만",
        "vibe": "로컬 감성",
        "meal_time": "점심",
        "rating_taste": 5,
        "rating_mood": 3,
        "rating_service": 4,
        "facilities": ["포장가능"],
        "memo": "부산 밀면의 원조라 해도 과언이 아님. 육수가 진하면서도 깔끔. 당면 추가는 필수. 부산 올 때마다 들르는 곳.",
        "revisit": True,
        "visited_date": datetime.date(2024, 2, 14),
    },
    {
        "name": "해운대 암소갈비집",
        "address": "부산 해운대구 해운대해변로 298",
        "region": "부산",
        "category": "고기",
        "price_range": "4만원대",
        "vibe": "로컬 감성",
        "meal_time": "저녁",
        "rating_taste": 5,
        "rating_mood": 4,
        "rating_service": 4,
        "facilities": ["주차", "단체석", "예약가능"],
        "memo": "숯불에 구운 암소 갈비가 부드럽고 육즙이 살아있음. 된장찌개와 냉면도 기본 이상. 가족 외식 최고.",
        "revisit": True,
        "visited_date": datetime.date(2024, 3, 1),
    },
    {
        "name": "범일동 할매국밥",
        "address": "부산 동구 범일로 107",
        "region": "부산",
        "category": "한식",
        "price_range": "1만원 미만",
        "vibe": "로컬 감성",
        "meal_time": "아침",
        "rating_taste": 5,
        "rating_mood": 2,
        "rating_service": 3,
        "facilities": [],
        "memo": "부산 돼지국밥 원탑. 새벽 5시부터 줄 서는 곳. 뼈를 우린 육수 깊이가 다르다. 내장 추가 강추.",
        "revisit": True,
        "visited_date": datetime.date(2024, 4, 20),
    },
    {
        "name": "광안리 수변최고집",
        "address": "부산 수영구 광안해변로 219",
        "region": "부산",
        "category": "해산물",
        "price_range": "2만원대",
        "vibe": "뷰 맛집",
        "meal_time": "저녁",
        "rating_taste": 4,
        "rating_mood": 5,
        "rating_service": 3,
        "facilities": ["야외석", "예약가능"],
        "memo": "광안대교 뷰 보면서 먹는 회가 이 맛. 뷰 가격 포함해서 생각하면 가성비 나쁘지 않음. 일몰 시간대에 가면 최고.",
        "revisit": True,
        "visited_date": datetime.date(2024, 6, 15),
    },
    # 제주
    {
        "name": "제주 흑돼지 오겹살 본점",
        "address": "제주 제주시 서광로 226",
        "region": "제주",
        "category": "고기",
        "price_range": "2만원대",
        "vibe": "로컬 감성",
        "meal_time": "저녁",
        "rating_taste": 5,
        "rating_mood": 4,
        "rating_service": 4,
        "facilities": ["주차", "단체석"],
        "memo": "제주 흑돼지는 역시 다르다. 오겹살 두께가 적당하고 껍데기까지 씹는 맛이 살아있음. 감귤 소금장과 먹으면 환상.",
        "revisit": True,
        "visited_date": datetime.date(2024, 1, 3),
    },
    {
        "name": "성산 고등어쌈밥",
        "address": "제주 서귀포시 성산읍 성산리 78",
        "region": "제주",
        "category": "해산물",
        "price_range": "1만원대",
        "vibe": "로컬 감성",
        "meal_time": "점심",
        "rating_taste": 5,
        "rating_mood": 3,
        "rating_service": 4,
        "facilities": ["주차", "포장가능"],
        "memo": "제주산 고등어를 연탄불에 구워 쌈 싸 먹는 조합이 완벽. 밑반찬이 8가지나 나오는데 다 맛있음. 가성비 최고.",
        "revisit": True,
        "visited_date": datetime.date(2024, 1, 4),
    },
    {
        "name": "카페 봄날 서귀포",
        "address": "제주 서귀포시 색달동 3039-1",
        "region": "제주",
        "category": "카페/디저트",
        "price_range": "1만원대",
        "vibe": "뷰 맛집",
        "meal_time": "오후",
        "rating_taste": 4,
        "rating_mood": 5,
        "rating_service": 4,
        "facilities": ["야외석", "주차"],
        "memo": "바다 전망이 압도적. 한라봉 에이드와 녹차 케이크가 제주 감성 물씬. 사진 찍으러 가는 느낌이지만 음료도 괜찮음.",
        "revisit": True,
        "visited_date": datetime.date(2024, 1, 5),
    },
    # 경주
    {
        "name": "황리단길 쌈밥한상",
        "address": "경북 경주시 포석로 1080",
        "region": "경주",
        "category": "한식",
        "price_range": "1만원대",
        "vibe": "고즈넉한",
        "meal_time": "점심",
        "rating_taste": 4,
        "rating_mood": 4,
        "rating_service": 4,
        "facilities": ["예약가능"],
        "memo": "황리단길 걷다 들어간 한상 차림 맛집. 제육볶음이 달지 않고 깔끔. 한옥 창문 너머 뷰도 좋았음.",
        "revisit": True,
        "visited_date": datetime.date(2024, 4, 27),
    },
    # 인천
    {
        "name": "인천 차이나타운 공화춘",
        "address": "인천 중구 차이나타운로 56-14",
        "region": "인천",
        "category": "중식",
        "price_range": "1만원대",
        "vibe": "레트로 / 빈티지",
        "meal_time": "점심",
        "rating_taste": 4,
        "rating_mood": 4,
        "rating_service": 3,
        "facilities": ["단체석", "포장가능"],
        "memo": "짜장면 원조 집. 관광지 밥집 느낌이지만 춘장 볶음 향이 진하고 면발이 쫄깃. 역사적 의미도 있어 한 번은 가볼 만.",
        "revisit": False,
        "visited_date": datetime.date(2024, 3, 9),
    },
    # 전주
    {
        "name": "전주 한옥마을 가족회관",
        "address": "전북 전주시 완산구 태조로 32",
        "region": "전주",
        "category": "한식",
        "price_range": "1만원대",
        "vibe": "고즈넉한",
        "meal_time": "점심",
        "rating_taste": 5,
        "rating_mood": 4,
        "rating_service": 4,
        "facilities": ["단체석", "주차", "예약가능"],
        "memo": "전주비빔밥의 정석. 육회비빔밥과 콩나물국밥 콤보가 최고. 반찬도 30가지 가까이 나옴. 전주 오면 무조건.",
        "revisit": True,
        "visited_date": datetime.date(2024, 5, 3),
    },
    # 강릉
    {
        "name": "강릉 교동짬뽕",
        "address": "강원 강릉시 교동 1-2",
        "region": "강릉",
        "category": "중식",
        "price_range": "1만원대",
        "vibe": "로컬 감성",
        "meal_time": "점심",
        "rating_taste": 5,
        "rating_mood": 3,
        "rating_service": 3,
        "facilities": ["포장가능"],
        "memo": "강릉 현지인 픽 짬뽕. 해산물이 가득하고 국물이 칼칼하면서 시원함. 볶음밥도 같이 시키면 완벽한 한 끼.",
        "revisit": True,
        "visited_date": datetime.date(2024, 7, 21),
    },
    {
        "name": "테라로사 강릉 본점",
        "address": "강원 강릉시 구정면 현천길 7",
        "region": "강릉",
        "category": "카페/디저트",
        "price_range": "1만원대",
        "vibe": "모던 / 세련된",
        "meal_time": "오후",
        "rating_taste": 5,
        "rating_mood": 5,
        "rating_service": 4,
        "facilities": ["주차", "야외석"],
        "memo": "한국 스페셜티 커피의 성지. 넓은 정원과 공장형 건물 분위기가 독특. 에스프레소 계열이 특히 탁월. 강릉 커피 여행 필수.",
        "revisit": True,
        "visited_date": datetime.date(2024, 7, 22),
    },
]


class Command(BaseCommand):
    help = "샘플 맛집 데이터를 DB에 채워 넣습니다."

    def handle(self, *args, **options):
        # 데모 유저 생성 (없으면)
        user, created = User.objects.get_or_create(
            username="matitda_demo",
            defaults={
                "nickname": "맛잇다지기",
                "email": "demo@matitda.kr",
            },
        )
        if created:
            user.set_password("demo1234!")
            user.save()
            self.stdout.write(self.style.SUCCESS(f"데모 유저 생성: {user.username}"))
        else:
            self.stdout.write(f"기존 유저 사용: {user.username}")

        created_count = 0
        for data in RESTAURANTS:
            _, is_new = Restaurant.objects.get_or_create(
                name=data["name"],
                user=user,
                defaults=data,
            )
            if is_new:
                created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"\n완료! {created_count}개 맛집 등록됨 (총 {len(RESTAURANTS)}개 중)"
            )
        )
